language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t benjaminhate/docker-udemy-course-test -f Dockerfile.dev .

script:
  - docker run -e CI=true benjaminhate/docker-udemy-course-test npm run test